### ISSUE TITLE
Hubot phabricator data corrupt upon restart

### ISSUE THREAD

**Issue by redstonemercury** [Gandi/hubot-phabs#11]
We're encountering an issue where upon restarting hubot the phabricator data from redis does not seem to be read in properly to this module.

Specifically, the phabricator data with feeds are visible in redis data under each project, and for feedall the rooms are listed (I've obfuscated the data):

```
myuser@myhost:~# redis-cli get "hubot:storage" | jq .phabricator
{
  "projects": {
    "*": {
      "feeds": [
        "noisybotroom"
      ]
    },
    "Project With Spaces": {
      "name": "Project With Spaces",
      "phid": "PHID-PROJ-xxxxxx",
      "parent": null,
      "columns": {
        "this_iteration": "PHID-PCOL-xxxxxx",
        "upcoming": "PHID-PCOL-xxxxxx",
        "backlog": "PHID-PCOL-xxxxxx"
      },
      "feeds": [
        "room1"
      ]
    },
    "Project-With-Dashes": {
      "name": "Project-With-Dashes",
      "phid": "PHID-PROJ-xxxxxx",
      "parent": null,
      "columns": {
        "backlog": "PHID-PCOL-xxxxxx",
        "working": "PHID-PCOL-xxxxxx",
        "waiting_on_others": "PHID-PCOL-xxxxxx"
      },
      "feeds": [
        "room2"
      ]
    },
    "Project3": {
      "name": "Project3",
      "phid": "PHID-PROJ-xxxxxx",
      "parent": null,
      "columns": {
        "waiting_on_others": "PHID-PCOL-xxxxxx",
        "backlog": "PHID-PCOL-xxxxxx"
      },
      "feeds": [
        "room2"
      ]
    },
    "Project4": {
      "name": "Project4",
      "phid": "PHID-PROJ-xxxxxx",
      "parent": null,
      "columns": {
        "current_iteration": "PHID-PCOL-xxxxxx",
        "backlog": "PHID-PCOL-xxxxxx",
        "waiting": "PHID-PCOL-xxxxxx"
      },
      "feeds": [
        "room3"
      ]
    }
  },
  "aliases": {
    "project_1": "Project With Spaces",
    "project_2": "Project-With-Dashes",
    "project_3": "Project3",
    "project_4": "Project4"
  },
  "templates": {},
  "blacklist": [],
  "users": {
    "me": {
      "name": "me",
      "id": "me",
      "phid": "PHID-USER-123456"
    },
    "SLACKID": {
      "name": "me",
      "id": "SLACKID",
      "phid": "PHID-USER-123456"
    }
  },
  "bot_phid": "hubot",
  "alerts": {
    "me": "PHID-USER-789012"
  }
}
```

Although the data is properly in redis, nothing will be fed into rooms after the hubot is restarted. I added debugging to `console.log` incoming feed events in `scripts/phabs_feeds.coffee` and verified events come through, but just aren't fed anywhere after a restart.

Asking hubot to feedall to a room that is already in redis data will recreate the feed (redis data does not change, but hubot says: `Ok, all feeds will be announced on 'noisybotroom'.`), and asking hubot to create a project -> room feed that should already exist will sometimes result in the feed being recreated (redis data does not change, but hubot says: `Ok, 'Project1' is now feeding 'room1'.`), but sometimes this seems to result in removal of the nested "feeds" object for that project, no hubot output to the user, and the exception below being thrown by hubot:

```
May  4 19:39:46 hubot[16077]: error: no_text
May  4 19:39:46 hubot[16077]: Unhandled rejection Error: no_text
May  4 19:39:46 hubot[16077]: at handleHttpResponse (/src/hubot/node_modules/@slack/client/lib/clients/transports/call-transport.js:105:17)
May  4 19:39:46 hubot[16077]: at handleTransportResponse (/src/hubot/node_modules/@slack/client/lib/clients/transports/call-transport.js:155:19)
May  4 19:39:46 hubot[16077]: at apply (/src/hubot/node_modules/@slack/client/node_modules/lodash/lodash.js:499:17)
May  4 19:39:46 hubot[16077]: at wrapper (/src/hubot/node_modules/@slack/client/node_modules/lodash/lodash.js:5356:16)
May  4 19:39:46 hubot[16077]: at Request.handleRequestTranportRes (/src/hubot/node_modules/@slack/client/lib/clients/transports/request.js:20:5)
May  4 19:39:46 hubot[16077]: at apply (/src/hubot/node_modules/@slack/client/node_modules/lodash/lodash.js:499:17)
May  4 19:39:46 hubot[16077]: at Request.wrapper [as _callback] (/src/hubot/node_modules/@slack/client/node_modules/lodash/lodash.js:5356:16)
May  4 19:39:46 hubot[16077]: at Request.self.callback (/src/hubot/node_modules/request/request.js:188:22)
May  4 19:39:46 hubot[16077]: at Request.emit (events.js:110:17)
May  4 19:39:46 hubot[16077]: at Request.<anonymous> (/src/hubot/node_modules/request/request.js:1171:10)
May  4 19:39:46 hubot[16077]: at Request.emit (events.js:107:17)
May  4 19:39:46 hubot[16077]: at IncomingMessage.<anonymous> (/src/hubot/node_modules/request/request.js:1091:12)
May  4 19:39:46 hubot[16077]: at IncomingMessage.g (events.js:199:16)
May  4 19:39:46 hubot[16077]: at IncomingMessage.emit (events.js:129:20)
May  4 19:39:46 hubot[16077]: at _stream_readable.js:908:16
May  4 19:39:46 hubot[16077]: at process._tickCallback (node.js:355:11)
```

This is my first time using coffeescript so am having a hard time debugging this myself, but I imagine the issue exists in the constructor where the data is being loaded or else defaulted https://github.com/Gandi/hubot-phabs/blob/master/lib/phabricator.coffee#L65-L82 We have projects with spaces in the name and also dashes in the names. The one with a space in the name is the one I'm seeing wipe the nested "feeds" object when I try to re-add it, but I've only restarted a handful of times (due to having to keep the bot running so people can use it) so I'm not sure if it's actually the problem, or just the one I happen to be noticing the most.

Right now the only way I've found to reliably fix this is by dropping the redis db with hubot data, restarting hubot to have it recreate the data structure anew, then sending the commands to hubot to have it rediscover the projects and recreate the feeds. Obviously this isn't a great solution since we need to be able to back up the config and stop/start hubot whenever we want.

Let me know if you need any more information to look into this, or if you have any suggestions to try/patches to test and I can look/test it out!

**Comment by mose** [comment]
This is pretty weird.

About project names, spaces and dashes should not be a problem, on my side I have plenty of them and there is no issue.

Maybe you are right about the brain loading, I applied https://github.com/Gandi/hubot-phabs/commit/e06adc1169a2932ee28ee7fbf427cbcb36f7c15c can you test this? Those default values are intended to be set for people that had brains from previous versions, it's like a migration path, but it fits better in the `.on `loaded'` block. On my side I use the file-brain and I have no issue. Different context.

About the `no_text` exception this is a different concern, probably related to the slack adapter. If we find a way to fix the feeding, and it's still there, we can talk more about this one.

Can you first try to change the defaults modification position (or even remove the default setup altogether, ie. everything after `storageLoaded()`) and see if it fares batter?

**Comment by redstonemercury** [comment]
Unfortunately, that didn't seem to do it. Same issues.

I added `console.log @data.projects` after the `@robot.logger.debug '---- Phabricator Data Loaded.'` line, and can see tailing syslog that it seems to have the proper data in the object itself, so I'm not sure what's going wrong...

Are you able to recreate this issue? Or is it just something with my setup?

**Comment by mose** [comment]
Okay, I tried the `hubot-redis-brain` and finally reproduced it. I'm not sure why it came to behave like this, but I made it work.

Can you try with version 2.4.9 ?

**Comment by redstonemercury** [comment]
Success! No more redis amnesia. Thank you so much for the quick turnaround on this! :100:
