### ISSUE TITLE
Task priority "100" is not a valid task priority

### ISSUE THREAD

**Issue by webcracy** [Gandi/hubot-phabs#13]
The way to specify a task priority using the Conduit API has changed since [this Phabricator update](https://secure.phabricator.com/w/changelog/2017.25/) (2017 Week 25 (Late June)).

> When changing task priorities with maniphest.edit, transactions now accept a keyword value like "high", not a numeric value like "75". This is a breaking change.

We have only recently upgraded our Phabricator instance and are now stuck whenever we try to set or change a task priority using `hubot-phabs`. Example:
```
user: .ph is unbreak
bot: Validation errors:
bot:   - Task priority "100" is not a valid task priority. Use a priority keyword to choose a task priority: unbreak, triage, high, normal, low, wish.
```

The current code tries to translate the keywords to numeric values:
*  https://github.com/Gandi/hubot-phabs/blob/9ba8fa37e19b64f17eceed3130293666f0f73ae5/lib/phabricator.coffee#L40-L52
* https://github.com/Gandi/hubot-phabs/blob/9ba8fa37e19b64f17eceed3130293666f0f73ae5/lib/phabricator.coffee#L822-L824

I guess a nice way to handle this would be to either return the mapped numeric value or the string (if it's a key in the same object), depending on the version of Phabricator that the bot is communicating with.

I'll try to submit a PR soon; don't hesitate to beat me to it or suggest other approaches.

**Comment by baptistem** [comment]
Hi Alexandre,

Thanks for picking this up.
I have a fix ready to be pushed upstream, you can expect it before monday.

I would have liked to avoid breaking compat with older phab version but it seems to be the way to do with phabricator.

thanks,

kolo

**Comment by mose** [comment]
Maybe you can add a config flag for `PHABRICATOR_VERSION` and initialize another `priorities` hash when more than `2017.25` ?

**Comment by mose** [comment]
That would also be applicable to the previous breaking change in fulltext search in `v2.4.11`, also, I think.
