### ISSUE TITLE
Mentioning diffusion revisions results in "[slug]undefined not found"

### ISSUE THREAD

**Issue by donaldguy** [Gandi/hubot-phabs#2]
<img width="712" alt="screen shot 2016-10-11 at 4 46 45 pm" src="https://cloud.githubusercontent.com/assets/43136/19288122/91b00d3e-8fd2-11e6-931f-4662fd4a2a89.png">
We are not currently using the feeds feature of your bot cause we just want all projects in one channel for now

I thought you might be expecting a non-prefix slug, but it didn't help
<img width="636" alt="screen shot 2016-10-11 at 4 48 52 pm" src="https://cloud.githubusercontent.com/assets/43136/19288134/9c008c46-8fd2-11e6-92dc-18fb479b5ee1.png">

**Comment by donaldguy** [comment]
same thing with a URL to a revision

**Comment by donaldguy** [comment]
Looking at https://github.com/Gandi/hubot-phabs/blob/a1f185acc0da94f74d8ac967e66300cfda7ef72d/scripts/phabs_hear.coffee I can't see an issue, but if there was an earlier revision that erroneously used the `"#{type}#{id}` on the `/r[A-Z]+[0-9a-f]{10,}/` match that would explain it

I am working off the npm version so maybe you need to do a new release

**Comment by mose** [comment]
You are perfectly right! It was a tiny regexp issue. Now fixed in 2.1.1

Thanks for reporting :+1:
