### ISSUE TITLE
feed cant search project info

### ISSUE THREAD

**Issue by svr678** [Gandi/hubot-phabs#5]
"phad feed new_project to a_room"
fail to add this feed, but:
"phad info new_project
phad feed new_project to a_room"
it works now, so could you please add something to the feed function, thanks a lot!
And we all like your plugin, it's very good for phabricator and hubot!

**Comment by mose** [comment]
Ah, yes, I could add the retrieval of projet info in the feed subcommand, if not found. It should not be long to have it in the next version of the plugin.

**Comment by mose** [comment]
Okay this should be solved by 9890c7c3b480459d0dd97bc325d2f567c94497e5 it will be shipped in next version 2.3.0 (coming soon).
