### ISSUE TITLE
support to feed all story or by author

### ISSUE THREAD

**Issue by svr678** [Gandi/hubot-phabs#6]
as title, hope to add the command to feed all story to a room;
or feed by authors(and memberof some_project);
Thanks in advance!

**Comment by mose** [comment]
Noted, I add this to my todo list :+1:

**Comment by svr678** [comment]
Great!

**Comment by mose** [comment]
The `.phad feedall to room` is available in 2.3.0, lets keep this issue open for the `by author/member` feature. 2.3.0 will be published in the next few days, I need some more testing.

**Comment by svr678** [comment]
sure, by author/member feature will be open;

in the 2.3.2, all "project related" messages are sent to the room, but not all messages, the message which not related to any project still can not be sent to room. does it need some settings to somewhere? Thanks a lot!

**Comment by mose** [comment]
oh, I will have a look into that case. Thanks for reporting it.

**Comment by svr678** [comment]
ok, that's great! :)

**Comment by mose** [comment]
Release 2.3.4 includes the possibility to add a new env var `PHABRICATOR_FEED_EVERYTHING`. Set it to '1' and the feedall will not only feed tasks but every other objects as well.

**Comment by svr678** [comment]
Works perfectly!~ Many thanks for your hard works! :+1:

**Comment by mose** [comment]
I added an option for having per-user alerts on tasks in 2.4.1. It may not be exactly what you had in mind but I hope you will find it useful. Let's close this ticket and open another one if you want notifications for all members of a project.
