### ISSUE TITLE
feed supports to know the subproject(milestone)

### ISSUE THREAD

**Issue by svr678** [Gandi/hubot-phabs#7]
As title, now we have to add all subprojects(milestones) to the room one by one, it works but a little bit annoying, could you please let feed know the subprojects of the project, thanks a lot!

**Comment by mose** [comment]
hmm, we don't use milestone here. I gotta have a look into that.

**Comment by mose** [comment]
Okay this one is implemented in 1bd567f81f8588e96a3c3451c852baec96379b4d and will be released in v2.3.0

**Comment by mose** [comment]
2.3.0 is now released :)
